const planetsImages = [
  { planet: 'Alderaan', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Alderaan.png' },
  { planet: 'Bespin', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Bespin.png' },
  { planet: 'Bestine IV', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Bestine_IV.png' },
  { planet: 'Cato Neimoidia', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Cato_Neimoidia.png' },
  { planet: 'Cerea', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Cerea.png' },
  { planet: 'Champala', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Champala.png' },
  { planet: 'Chandrila', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Chandrila.png' },
  { planet: 'Corellia', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Corellia.png' },
  { planet: 'Coruscant', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Coruscant.png' },
  { planet: 'Dagobah', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Dagobah.png' },
  { planet: 'Dantooine', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Dantooine.png' },
  { planet: 'Dathomir', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Dathomir.png' },
  { planet: 'Dorin', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Dorin.png' },
  { planet: 'Endor', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Endor.png' },
  { planet: 'Eriadu', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Eriadu.png' },
  { planet: 'Felucia', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Felucia.png' },
  { planet: 'Geonosis', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Geonosis.png' },
  { planet: 'Haruun Kal', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Haruun_Kal.png' },
  { planet: 'Hoth', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Hoth.png' },
  { planet: 'Iktotch', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Iktotch.png' },
  { planet: 'Iridonia', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Iridonia.png' },
  { planet: 'Kamino', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Kamino.png' },
  { planet: 'Kashyyyk', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Kashyyyk.png' },
  { planet: 'Malastare', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Malastare.png' },
  { planet: 'Mon Cala', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Mon_Cala.png' },
  { planet: 'Mustafar', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Mustafar.png' },
  { planet: 'Mygeeto', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Mygeeto.png' },
  { planet: 'Naboo', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Naboo.png' },
  { planet: 'Nal Hutta', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Nal_Hutta.png' },
  { planet: 'Ord Mantell', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Ord_Mantell.png' },
  { planet: 'Polis Massa', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Polis_Massa.png' },
  { planet: 'Rodia', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Rodia.png' },
  { planet: 'Ryloth', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Ryloth.png' },
  { planet: 'Saleucami', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Saleucami.png' },
  { planet: 'Socorro', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Socorro.png' },
  { planet: 'Sullust', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Sullust.png' },
  { planet: 'Tatooine', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Tatooine.png' },
  { planet: 'Toydaria', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Toydaria.png' },
  { planet: 'Trandosha', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Trandosha.png' },
  { planet: 'Utapau', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Utapau.png' },
  { planet: 'Vulpter', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Vulpter.png' },
  { planet: 'Yavin IV', image: 'https://s3.amazonaws.com/fellipekrein.com.br-new/starwars/Yavin_IV.png' },
];

export default planetsImages;
